.TH HPTKILL 1 "hptkill (v1.10)"
.SH NAME
hptkill \- Echoarea removal tool
.SH SYNOPSYS
.TP
.B hptkill
.B [ -c config ]
.B [ -1 ]
.B [ -n ]
.B [ -a ]
.B [ -d ]
.B [ -s ]
.br
.B [ -f file ]
.B [ -k ]
.B [ -p ]
.B [ -pp ]
.B [ -y ]
.B [ -yp ]
.br
.B [ -o days ]
.B [ -O days ]
.B [ -l file ]
.B [ -C ]
.br
.B [areaNameMask ...]
.RE
.SH DESCRIPTION
hptkill is a tool for killing echoareas from config and send unsubscribe
messages to all links for this area. It also can search and kill passthrough
areas with only one link.
.SH OPTIONS
.TP 10
.B \-c config
specify alternate config file
.TP 10
.B \-1
send unsubscribe message only to first link
.TP 10
.B \-n
don't send unsubscribe messages
.TP 10
.B \-a
send unsubscribe messages to all subscribed links
.TP 10
.B \-d
delete area from config
.TP 10
.B \-s
keep (save) message & dupe bases
.TP 10
.B \-f file
read areas list from file in addition to args
.TP 10
.B \-f -
read areas list from stdin in addition to args
.TP 10
.B \-k
set Kill/Sent attribute to messages for links
.TP 10
.B \-p
find & kill passthrough echoareas with <= 1 links
.TP 10
.B \-pp
same as -p including paused links
.TP 10
.B \-y
find & kill ALL echoareas with <=1 links
.TP 10
.B \-yp
same as -y including paused links
.TP 10
.B \-o days
kill passthrough area with dupebase older 'days' days
.TP 10
.B \-O days
same as -o but kill areas without dupebases
.TP 10
.B \-l file
with -o/-O write a list of areas without dupebase to file
.TP 10
.B \-C
create empty dupebase if it doesn't exist
.SH DEFAULT SETTINGS:
send unsubscribe message to subcribed nodes only
.br
leave config unchanged
.br
erase message & dupe bases
.SH ENVIROMENT
.B FIDOCONFIG
.PP
path/filename of the husky configuration file
.SH AUTHOR
Serguei Revtov 2:5021/11.10 or/and 2:5021/19.1
.br
This manual page was originally written by Pavel Andreew
<pavel@collage.etel.ru>.
