CC       = gcc
CFLAGS   = -c -g -Wall -O2 -DUNIX -I./h -I/usr/src/packages
LFLAGS   = -s -L../fidoconf -L../smapi

OBJS    = hptkill.o
SRC_DIR = src/
#STATIC = -static

all: $(OBJS) \
	hptkill

%.o: $(SRC_DIR)%.c
	$(CC) $(CFLAGS) $(SRC_DIR)$*.c

hptkill: $(OBJS)
	$(CC) $(LFLAGS) $(STATIC) -o hptkill $(OBJS) -lsmapilnx -lfidoconfiglnx

clean:
	-rm -f *.o
	-rm -f *~
	-rm -f hptkill
	-rm -f core
