# $Id$
#
# Microsoft Visual C++ Makefile for build hptkill static library

CC	= cl
RM	= del

CFLAGS	= -nologo -Zp1 -I..\..
CDEFS	= -D__NT__ -D_CONSOLE
COPT	= -O2
TLIB	= lib -nologo

LIBS	= ..\..\smapi\smapimvc.lib ..\..\fidoconf\fconfmvc.lib

EXENAMEFLAG = -Fe

OBJ	= .obj
EXE	= .exe

TARGET	= hptkill$(EXE)

all: $(TARGET)

$(TARGET):
        $(CC) $(CFLAGS) $(CDEFS) $(COPT) $(EXENAMEFLAG)$@ ..\src\hptkill.c $(LIBS)

clean:
	-$(RM) *$(OBJ)

distclean: clean
	-$(RM) $(TARGET)
