# Microsoft Visual C++ Makefile

CC=     cl
CFLAGS= -nologo -Zp1 -I..\..
CDEFS=  -D__NT__ -DNT -DWINNT -D_CONSOLE
COPT=   -O2
TLIB=   lib -nologo

SMAPIL=	..\..\smapi\smapimvc.lib
FCONFL=	..\..\fidoconf\fconfmvc.lib

all: hptkill.exe

hptkill.exe:
        $(CC) $(CFLAGS) $(CDEFS) $(COPT) -Fe$@ ..\src\hptkill.c $(FCONFL) $(SMAPIL)

clean:
	-del *.obj

distclean: clean
	-del *.exe
